name: RapidLearningInMemoryComputing
channels:
  - conda
  - anaconda
  - defaults
dependencies:
  - hdf5=1.10.6
  - python=3.9.5
  - readline=8.1
  - scipy=1.7.3
  - tk=8.6.10
  - pip:
    - aim
    - aim-ui
    - aimrecords
    - aimrocks
    - h5py==3.1.0
    - ipykernel==6.29.2
    - keras==2.6.0
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.6
    - pandas==1.3.0
    - pandocfilters==1.5.1
    - pip==24.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - tensorboard==2.6.0
    - tensorflow==2.5.0
    - tensorflow-datasets==4.4.0
    - tensorflow-estimator==2.5.0
    - tensorflow-metadata==1.4.0
    - tensorflow-probability==0.13.0
    - tqdm==4.62.3
    - werkzeug==2.0.1
